name: Deploy to Heroku

on:
  workflow_dispatch:
    branches:
      -main
  push:
    branches:
      - main

env:
  DB_DIALECT: mysql
  DB_DATABASE: ${{secrets.DB_DATABASE}}
  DB_HOST: ${{secrets.DB_HOST}}
  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
  DB_USERNAME: ${{secrets.DB_USERNAME}}
  NODE_ENV: production

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm run server:test

  frontend-test:
    runs-on: ubuntu-latest
    needs: backend-test
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - run: cd client && npm install
      - run: npm run client:test

  build:
    runs-on: ubuntu-latest
    needs: frontend-test
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: 'npm'
          cache-dependency-path: |
            client/package-lock.json
            package-lock.json
      - run: cd client && npm install
      - run: npm install
      - run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "super-hero-app-hjamison"
          heroku_email: "hollisjamison@gmail.com"
